# Generated by Django 5.0.6 on 2024-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0002_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="guzzler",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="mpg_data",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="s_charger",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="t_charger",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
