# Generated by Django 5.0.6 on 2024-05-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0003_alter_vehicle_guzzler_alter_vehicle_mpg_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="epa_range_for_fuel_type2",
            field=models.CharField(blank=True, null=True),
        ),
    ]
